import type {
  Work,
  WorkSummary,
  LibraryEntry,
  Collection,
  ReadingHistoryItem,
  DownloadItem,
  Genre,
  Author,
  Publisher,
  Volume,
  Chapter,
  Character,
} from '@/types/library'

// ── Genres ─────────────────────────────────────────────────────────────────
export const LIBRARY_GENRES: Genre[] = [
  { id: 'action', name: 'Action' },
  { id: 'adventure', name: 'Aventure' },
  { id: 'comedy', name: 'Comédie' },
  { id: 'drama', name: 'Drame' },
  { id: 'fantasy', name: 'Fantaisie' },
  { id: 'horror', name: 'Horreur' },
  { id: 'mystery', name: 'Mystère' },
  { id: 'psychological', name: 'Psychologique' },
  { id: 'romance', name: 'Romance' },
  { id: 'sci-fi', name: 'Sci-Fi' },
  { id: 'seinen', name: 'Seinen' },
  { id: 'shonen', name: 'Shonen' },
  { id: 'slice-of-life', name: 'Tranche de vie' },
  { id: 'sports', name: 'Sports' },
  { id: 'supernatural', name: 'Surnaturel' },
  { id: 'thriller', name: 'Thriller' },
]

// ── Authors ────────────────────────────────────────────────────────────────
export const AUTHORS: Record<string, Author> = {
  hiro: { id: 'hiro', name: 'Hiro Mashima', avatarUrl: '/kami-sama.png' },
  eiichiro: { id: 'eiichiro', name: 'Eiichiro Oda', avatarUrl: '/kami-sama.png' },
  kentaro: { id: 'kentaro', name: 'Kentaro Miura', avatarUrl: '/kami-sama.png' },
  takeshi: { id: 'takeshi', name: 'Takeshi Obata', avatarUrl: '/kami-sama.png' },
  yuki: { id: 'yuki', name: 'Yuki Tabata', avatarUrl: '/kami-sama.png' },
  koyoharu: { id: 'koyoharu', name: 'Koyoharu Gotouge', avatarUrl: '/kami-sama.png' },
  hajime: { id: 'hajime', name: 'Hajime Isayama', avatarUrl: '/kami-sama.png' },
  masashi: { id: 'masashi', name: 'Masashi Kishimoto', avatarUrl: '/kami-sama.png' },
  tsugumi: { id: 'tsugumi', name: 'Tsugumi Ohba', avatarUrl: '/kami-sama.png' },
  nob: { id: 'nob', name: 'Nobuaki Kaneshiro', avatarUrl: '/kami-sama.png' },
  park: { id: 'park', name: 'Park Jin-Hwan', avatarUrl: '/kami-sama.png' },
  lee: { id: 'lee', name: 'Lee Jong-Young', avatarUrl: '/kami-sama.png' },
  urasawa: { id: 'urasawa', name: 'Naoki Urasawa', avatarUrl: '/kami-sama.png' },
  suu: { id: 'suu', name: 'Suu Minazuki', avatarUrl: '/kami-sama.png' },
  okamoto: { id: 'okamoto', name: 'Kentaro Okamoto', avatarUrl: '/kami-sama.png' },
}

// ── Publishers ─────────────────────────────────────────────────────────────
export const PUBLISHERS: Record<string, Publisher> = {
  kodansha: { id: 'kodansha', name: 'Kodansha' },
  shueisha: { id: 'shueisha', name: 'Shueisha' },
  shogakukan: { id: 'shogakukan', name: 'Shogakukan' },
  kadokawa: { id: 'kadokawa', name: 'Kadokawa' },
  viz: { id: 'viz', name: 'VIZ Media' },
  delcourt: { id: 'delcourt', name: 'Delcourt/Tonkam' },
  kaze: { id: 'kaze', name: 'Kazé' },
  panini: { id: 'panini', name: 'Panini Comics' },
  glenat: { id: 'glenat', name: 'Glénat' },
  tokyopop: { id: 'tokyopop', name: 'Tokyopop' },
  naver: { id: 'naver', name: 'Naver Series' },
  kakao: { id: 'kakao', name: 'Kakao Page' },
}

// ── Works ──────────────────────────────────────────────────────────────────
export const LIBRARY_WORKS: Work[] = [
  {
    id: 'w1',
    slug: 'berserk-the-golden-age',
    type: 'manga',
    title: "Berserk — L'Âge d'Or",
    alternativeTitles: ['ベルセルク', 'Berserk'],
    synopsis: 'Guts, un guerrier solitaire au bras gauche remplacé par une prothèse de fer et à une lame gigantesque sur le dos, erre dans un monde de fantasy sombre peuplé de démons et de traîtres. Ancien membre de la Bande du Faucon, un groupe de mercenaires, il est consumé par la soif de vengeance contre le demon qui a tout détruit.',
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'dark-fantasy', name: 'Dark Fantasy' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [AUTHORS.kentaro],
    publishers: [PUBLISHERS.kodansha, PUBLISHERS.glentat],
    status: 'ongoing',
    year: 1989,
    rating: 9.8,
    ratingCount: 12450,
    volumes: Array.from({ length: 42 }, (_, i) => ({
      id: `berserk-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200 + Math.floor(Math.random() * 50),
      releaseDate: `${1990 + Math.floor(i / 2)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    chapters: Array.from({ length: 380 }, (_, i) => ({
      id: `berserk-c${i + 1}`,
      number: i + 1,
      pageCount: 18 + Math.floor(Math.random() * 8),
      releaseDate: `${1990 + Math.floor(i / 30)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 380,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'deluxe', 'digital'],
    tags: ['épique', 'violence', 'drame'],
    themes: ['vengeance', 'destin', 'pouvoir'],
    universe: 'Berserk',
    mainCharacters: [
      { id: 'guts', name: 'Guts', role: 'main' },
      { id: 'griffith', name: 'Griffith', role: 'main' },
      { id: 'casca', name: 'Casca', role: 'main' },
    ],
  },
  {
    id: 'w2',
    slug: 'one-piece',
    type: 'manga',
    title: 'One Piece',
    alternativeTitles: ['ワンピース'],
    synopsis: "Monkey D. Luffy, un jeune garçon dont le corps a gagné des propriétés élastiques après avoir mangé un fruit du diable, rêve de devenir le Roi des Pirates en trouvant le trésor légendaire One Piece.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'comedy', name: 'Comédie' },
      { id: 'shonen', name: 'Shonen' },
    ],
    authors: [AUTHORS.eiichiro],
    publishers: [PUBLISHERS.shueisha, PUBLISHERS.glenat],
    status: 'ongoing',
    year: 1997,
    rating: 9.5,
    ratingCount: 18200,
    volumes: Array.from({ length: 107 }, (_, i) => ({
      id: `op-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 190 + Math.floor(Math.random() * 30),
      releaseDate: `${1997 + Math.floor(i / 2)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    chapters: Array.from({ length: 1120 }, (_, i) => ({
      id: `op-c${i + 1}`,
      number: i + 1,
      pageCount: 17 + Math.floor(Math.random() * 6),
      releaseDate: `${1997 + Math.floor(i / 50)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 1120,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital'],
    tags: ['aventure', 'amitié', 'pirates'],
    themes: ['liberté', 'rêves', 'amitié'],
    universe: 'One Piece',
    mainCharacters: [
      { id: 'luffy', name: 'Monkey D. Luffy', role: 'main' },
      { id: 'zoro', name: 'Roronoa Zoro', role: 'main' },
      { id: 'nami', name: 'Nami', role: 'main' },
    ],
  },
  {
    id: 'w3',
    slug: 'solo-leveling',
    type: 'manhwa',
    title: 'Solo Leveling',
    alternativeTitles: ['나 혼자만 레벨업', 'Ore dake Level Up na Ken'],
    synopsis: "Dans un monde où des portails dimensionnels reliant des donjons peuplés de monstres sont apparus, Sung Jin-Woo, le chasseur le plus faible de l'humanité, découvre un système de niveau secret qui lui permet de monter en puissance sans limites.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'fantasy', name: 'Fantaisie' },
    ],
    authors: [AUTHORS.chugong],
    illustrators: [AUTHORS.dubu],
    publishers: [PUBLISHERS.kakao, PUBLISHERS.kaze],
    status: 'completed',
    year: 2018,
    rating: 9.2,
    ratingCount: 9800,
    volumes: Array.from({ length: 8 }, (_, i) => ({
      id: `sl-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 250,
      releaseDate: `${2020 + i}-01-01`,
    })),
    chapters: Array.from({ length: 200 }, (_, i) => ({
      id: `sl-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2018 + Math.floor(i / 50)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 200,
    languages: ['fr', 'en', 'ko'],
    formats: ['digital', 'deluxe'],
    tags: ['progression', 'pouvoir', 'donjons'],
    themes: ['montée en puissance', 'éveil', 'solitaire'],
    universe: 'Solo Leveling',
    mainCharacters: [
      { id: 'jinwoo', name: 'Sung Jin-Woo', role: 'main' },
    ],
  },
  {
    id: 'w4',
    slug: 'death-note',
    type: 'manga',
    title: 'Death Note',
    alternativeTitles: ['デスノート'],
    synopsis: "Light Yagami, un lycéen brillant, trouve un cahier surnaturel qui donne le pouvoir de tuer quiconque dont le nom est écrit dedans. Il décide d'éliminer les criminels et de créer un monde nouveau, mais un detective mystérieux nommé L est sur ses traces.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'mystery', name: 'Mystère' },
      { id: 'psychological', name: 'Psychologique' },
      { id: 'thriller', name: 'Thriller' },
      { id: 'shonen', name: 'Shonen' },
    ],
    authors: [AUTHORS.tsugumi, AUTHORS.takeshi],
    publishers: [PUBLISHERS.shueisha, PUBLISHERS.kaze],
    status: 'completed',
    year: 2003,
    rating: 9.3,
    ratingCount: 14500,
    volumes: Array.from({ length: 12 }, (_, i) => ({
      id: `dn-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 190,
      releaseDate: `${2003 + Math.floor(i / 4)}-01-01`,
    })),
    chapters: Array.from({ length: 108 }, (_, i) => ({
      id: `dn-c${i + 1}`,
      number: i + 1,
      pageCount: 19,
      releaseDate: `${2003 + Math.floor(i / 20)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 108,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital', 'collector'],
    tags: ['jeu mental', 'justice', 'pouvoir'],
    themes: ['morale', 'pouvoir absolu', 'justice'],
    mainCharacters: [
      { id: 'light', name: 'Light Yagami', role: 'main' },
      { id: 'l', name: 'L', role: 'main' },
    ],
  },
  {
    id: 'w5',
    slug: 'tower-of-god',
    type: 'manhwa',
    title: 'Tower of God',
    alternativeTitles: ['신의 탑', 'Kami no Tou'],
    synopsis: "Twenty-Fifth Bam suit sa meilleure amie Rachel qui désire grimper la Tour. Pour la retrouver, il devra lui-même affronter les épreuves de la Tour, chacune plus dangereuse que la précédente, tout en découvrant les secrets de ce monde vertigineux.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'fantasy', name: 'Fantaisie' },
      { id: 'mystery', name: 'Mystère' },
    ],
    authors: [AUTHORS.lee],
    illustrators: [AUTHORS.park],
    publishers: [PUBLISHERS.naver, PUBLISHERS.kaze],
    status: 'ongoing',
    year: 2010,
    rating: 8.9,
    ratingCount: 7200,
    volumes: Array.from({ length: 12 }, (_, i) => ({
      id: `tog-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 220,
      releaseDate: `${2018 + i}-01-01`,
    })),
    chapters: Array.from({ length: 600 }, (_, i) => ({
      id: `tog-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2010 + Math.floor(i / 50)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 600,
    languages: ['fr', 'en', 'ko'],
    formats: ['digital', 'tankobon'],
    tags: ['tour', 'pouvoirs', 'alliances'],
    themes: ['ambition', 'trahison', 'montée en puissance'],
    universe: 'Tower of God',
    mainCharacters: [
      { id: 'bam', name: 'Twenty-Fifth Bam', role: 'main' },
      { id: 'rachel', name: 'Rachel', role: 'main' },
    ],
  },
  {
    id: 'w6',
    slug: 'monster',
    type: 'manga',
    title: 'Monster',
    alternativeTitles: ['モンスター'],
    synopsis: "Le Dr Kenzo Tenma, un chirurgien brillant, choisit de sauver la vie d'un jeune garçon au lieu du maire. Ce garçon se révèle être un tueur en série psychopathe. Tenma devra le traquer à travers l'Europe pour réparer son erreur.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'thriller', name: 'Thriller' },
      { id: 'mystery', name: 'Mystère' },
      { id: 'psychological', name: 'Psychologique' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [AUTHORS.urasawa],
    publishers: [PUBLISHERS.shogakukan, PUBLISHERS.kazé],
    status: 'completed',
    year: 1994,
    rating: 9.4,
    ratingCount: 6800,
    volumes: Array.from({ length: 18 }, (_, i) => ({
      id: `monster-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200,
      releaseDate: `${1994 + Math.floor(i / 4)}-01-01`,
    })),
    chapters: Array.from({ length: 162 }, (_, i) => ({
      id: `monster-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${1994 + Math.floor(i / 15)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 162,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'omnibus', 'digital'],
    tags: ['psychologique', 'chasse', 'Europe'],
    themes: ['morale', 'identité', 'nature humaine'],
    mainCharacters: [
      { id: 'tenma', name: 'Kenzo Tenma', role: 'main' },
      { id: 'johan', name: 'Johan Liebert', role: 'main' },
    ],
  },
  {
    id: 'w7',
    slug: 'mushoku-tensei',
    type: 'light-novel',
    title: 'Mushoku Tensei',
    alternativeTitles: ['無職転生', 'Mushoku Tensei: Jobless Reincarnation'],
    synopsis: "Un homme de 34 ans au chômage, sans amis ni ambitions, est reincarné dans un monde de fantasy avec tous ses souvenirs. Désireux de vivre une seconde chance sans les erreurs de sa vie passée, il va s'efforcer de devenir un mage puissant tout en tissant de vrais liens.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'fantasy', name: 'Fantaisie' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'slice-of-life', name: 'Tranche de vie' },
    ],
    authors: [{ id: 'rifujin', name: 'Rifujin na Magonote', avatarUrl: '/kami-sama.png' }],
    illustrators: [{ id: 'shirotaka', name: 'ShiroTaka', avatarUrl: '/kami-sama.png' }],
    publishers: [PUBLISHERS.kadokawa, PUBLISHERS.kaze],
    status: 'completed',
    year: 2012,
    rating: 9.0,
    ratingCount: 5400,
    volumes: Array.from({ length: 26 }, (_, i) => ({
      id: `mt-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 300,
      releaseDate: `${2014 + Math.floor(i / 4)}-01-01`,
    })),
    chapters: Array.from({ length: 280 }, (_, i) => ({
      id: `mt-c${i + 1}`,
      number: i + 1,
      pageCount: 25,
      releaseDate: `${2012 + Math.floor(i / 25)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 280,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital'],
    tags: ['isekai', 'reincarnation', 'magie'],
    themes: ['deuxième chance', 'croissance', 'famille'],
    universe: 'Mushoku Tensei',
    mainCharacters: [
      { id: 'rudeus', name: 'Rudeus Greyrat', role: 'main' },
    ],
  },
  {
    id: 'w8',
    slug: 'omniscient-reader',
    type: 'webtoon',
    title: 'Omniscient Reader\'s Viewpoint',
    alternativeTitles: ['전지적 독자 시점', 'ORV'],
    synopsis: "Kim Dokja, le seul lecteur d'un roman web de 3000 chapitres, se retrouve soudainement piégé dans l'univers de ce roman. Grâce à sa connaissance exhaustive de l'histoire, il va tenter de survivre et de changer le destin de ce monde.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'fantasy', name: 'Fantaisie' },
      { id: 'mystery', name: 'Mystère' },
      { id: 'psychological', name: 'Psychologique' },
    ],
    authors: [AUTHORS.lee],
    illustrators: [AUTHORS.park],
    publishers: [PUBLISHERS.naver, PUBLISHERS.kakao],
    status: 'completed',
    year: 2018,
    rating: 9.6,
    ratingCount: 8900,
    volumes: Array.from({ length: 10 }, (_, i) => ({
      id: `orv-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 250,
      releaseDate: `${2022 + i}-01-01`,
    })),
    chapters: Array.from({ length: 250 }, (_, i) => ({
      id: `orv-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2018 + Math.floor(i / 30)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 250,
    languages: ['fr', 'en', 'ko'],
    formats: ['digital', 'deluxe'],
    tags: ['survie', 'constellations', 'scénarios'],
    themes: ['destin', 'sacrifice', 'connaissance'],
    universe: 'ORV',
    mainCharacters: [
      { id: 'dokja', name: 'Kim Dokja', role: 'main' },
      { id: 'yoojoonghyuk', name: 'Yoo Joonghyuk', role: 'main' },
    ],
  },
  {
    id: 'w9',
    slug: 'vinland-saga',
    type: 'manga',
    title: 'Vinland Saga',
    alternativeTitles: ['ヴィンランド・サガ'],
    synopsis: "Thorfinn, fils d'un guerrier viking légendaire, grandit dans le but de venger la mort de son père. Il rejoint le groupe de mercenaires de son assassin pour affronter l'homme qui l'a tué, tout en découvrant ce que signifie vraiment être un guerrier.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'drama', name: 'Drame' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [{ id: 'makoto', name: 'Makoto Yukimura', avatarUrl: '/kami-sama.png' }],
    publishers: [PUBLISHERS.kodansha, PUBLISHERS.kaze],
    status: 'completed',
    year: 2005,
    rating: 9.3,
    ratingCount: 7100,
    volumes: Array.from({ length: 27 }, (_, i) => ({
      id: `vs-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200,
      releaseDate: `${2005 + Math.floor(i / 3)}-01-01`,
    })),
    chapters: Array.from({ length: 200 }, (_, i) => ({
      id: `vs-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2005 + Math.floor(i / 20)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 200,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital'],
    tags: ['Vikings', 'histoire', 'vengeance'],
    themes: ['paix', 'guerre', 'identité'],
    mainCharacters: [
      { id: 'thorfinn', name: 'Thorfinn', role: 'main' },
      { id: 'askeladd', name: 'Askeladd', role: 'main' },
    ],
  },
  {
    id: 'w10',
    slug: 'the-beginning-after-the-end',
    type: 'manhwa',
    title: 'The Beginning After the End',
    alternativeTitles: ['TBATE'],
    synopsis: "King Grey, un roi tout-puissant dans un monde médiéval, est reincarné dans un monde de magie sous la forme d'un jeune garçon nommé Arthur Leywin. Il va utiliser son expérience de vie passée pour protéger sa nouvelle famille et maîtriser la magie.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'fantasy', name: 'Fantaisie' },
      { id: 'adventure', name: 'Aventure' },
    ],
    authors: [{ id: 'turtleme', name: 'TurtleMe', avatarUrl: '/kami-sama.png' }],
    publishers: [PUBLISHERS.kakao],
    status: 'ongoing',
    year: 2018,
    rating: 8.8,
    ratingCount: 6200,
    volumes: Array.from({ length: 8 }, (_, i) => ({
      id: `tbate-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 240,
      releaseDate: `${2021 + i}-01-01`,
    })),
    chapters: Array.from({ length: 220 }, (_, i) => ({
      id: `tbate-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2018 + Math.floor(i / 30)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 220,
    languages: ['fr', 'en'],
    formats: ['digital', 'tankobon'],
    tags: ['isekai', 'magie', 'montée en puissance'],
    themes: ['renaissance', 'protection', 'famille'],
    mainCharacters: [
      { id: 'arthur', name: 'Arthur Leywin', role: 'main' },
    ],
  },
  {
    id: 'w11',
    slug: 'vagabond',
    type: 'manga',
    title: 'Vagabond',
    alternativeTitles: ['バガボンド'],
    synopsis: "Basé sur la vie de Miyamoto Musashi, ce manga raconte le parcours du plus grand sabreur du Japon. Shinmen Takezo, rebaptisé Miyamoto Musashi, erre à travers le Japon féodal à la recherche de l'éclaircie et du sens de la vie à travers le combat.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'drama', name: 'Drame' },
      { id: 'historical', name: 'Historique' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [AUTHORS.takehiko],
    publishers: [PUBLISHERS.kodansha],
    status: 'hiatus',
    year: 1998,
    rating: 9.5,
    ratingCount: 5600,
    volumes: Array.from({ length: 37 }, (_, i) => ({
      id: `vaga-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200,
      releaseDate: `${1999 + Math.floor(i / 3)}-01-01`,
    })),
    chapters: Array.from({ length: 327 }, (_, i) => ({
      id: `vaga-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${1998 + Math.floor(i / 25)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 327,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital'],
    tags: ['samouraï', 'art martiaux', 'philosophie'],
    themes: ['voie du sabre', 'perfectionnement', 'solitude'],
    mainCharacters: [
      { id: 'musashi', name: 'Miyamoto Musashi', role: 'main' },
    ],
  },
  {
    id: 'w12',
    slug: 'one-punch-man',
    type: 'manga',
    title: 'One-Punch Man',
    alternativeTitles: ['ワンパンマン'],
    synopsis: "Saitama, un héros qui peut vaincre n'importe quel ennemi d'un seul coup, est ennuyé par le manque de défis. Il cherche un adversaire digne de ce nom tout en protégeant la Terre des monstres.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'comedy', name: 'Comédie' },
      { id: 'sci-fi', name: 'Sci-Fi' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [{ id: 'one', name: 'ONE', avatarUrl: '/kami-sama.png' }],
    illustrators: [AUTHORS.murata],
    publishers: [PUBLISHERS.shueisha, PUBLISHERS.kaze],
    status: 'ongoing',
    year: 2009,
    rating: 8.9,
    ratingCount: 8700,
    volumes: Array.from({ length: 30 }, (_, i) => ({
      id: `opm-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200,
      releaseDate: `${2012 + Math.floor(i / 3)}-01-01`,
    })),
    chapters: Array.from({ length: 200 }, (_, i) => ({
      id: `opm-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2009 + Math.floor(i / 20)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 200,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'digital'],
    tags: ['super-héros', 'parodie', 'combat'],
    themes: ['puissance', 'ennui', 'héroïsme'],
    mainCharacters: [
      { id: 'saitama', name: 'Saitama', role: 'main' },
      { id: 'genos', name: 'Genos', role: 'main' },
    ],
  },
  {
    id: 'w13',
    slug: 'solo-max-level-newbie',
    type: 'manhwa',
    title: 'Solo Max-Level Newbie',
    alternativeTitles: ['나 혼자 네버 레벨업'],
    synopsis: "Jin-Hyuk, le premier joueur à avoir terminé le jeu « Tower of Trials », découvre que le monde réel est devenu le jeu. Grâce à sa connaissance parfaite de chaque mécanique et secret du jeu, il va devenir le joueur le plus puissant.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'adventure', name: 'Aventure' },
      { id: 'fantasy', name: 'Fantaisie' },
    ],
    authors: [{ id: 'maslow', name: 'Maslow', avatarUrl: '/kami-sama.png' }],
    publishers: [PUBLISHERS.kakao],
    status: 'ongoing',
    year: 2022,
    rating: 8.5,
    ratingCount: 3200,
    volumes: Array.from({ length: 4 }, (_, i) => ({
      id: `smln-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 250,
      releaseDate: `${2023 + i}-01-01`,
    })),
    chapters: Array.from({ length: 80 }, (_, i) => ({
      id: `smln-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${2022 + Math.floor(i / 30)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 80,
    languages: ['fr', 'en'],
    formats: ['digital'],
    tags: ['jeu vidéo', 'montée en puissance', '攻略'],
    themes: ['knowledge', 'pouvoir', 'stratégie'],
    mainCharacters: [
      { id: 'jinhyuk', name: 'Jin-Hyuk', role: 'main' },
    ],
  },
  {
    id: 'w14',
    slug: '20th-century-boys',
    type: 'manga',
    title: '20th Century Boys',
    alternativeTitles: ['20世紀少年'],
    synopsis: "Kenji Endo et ses amis d'enfance découvrent qu'un groupe terroriste utilise le symbole de leur club secret d'enfance. Pour sauver le monde, Kenji doit affronter le passé et l'identité du mystérieux « Ami ».",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'mystery', name: 'Mystère' },
      { id: 'sci-fi', name: 'Sci-Fi' },
      { id: 'thriller', name: 'Thriller' },
      { id: 'seinen', name: 'Seinen' },
    ],
    authors: [AUTHORS.urasawa],
    publishers: [PUBLISHERS.shogakukan],
    status: 'completed',
    year: 1999,
    rating: 9.1,
    ratingCount: 4800,
    volumes: Array.from({ length: 22 }, (_, i) => ({
      id: `20c-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 200,
      releaseDate: `${1999 + Math.floor(i / 4)}-01-01`,
    })),
    chapters: Array.from({ length: 200 }, (_, i) => ({
      id: `20c-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: `${1999 + Math.floor(i / 18)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 200,
    languages: ['fr', 'en', 'ja'],
    formats: ['tankobon', 'omnibus', 'digital'],
    tags: ['complot', 'nostalgie', 'apocalypse'],
    themes: ['amitié', 'destin', 'mémoire'],
    mainCharacters: [
      { id: 'kenji', name: 'Kenji Endo', role: 'main' },
    ],
  },
  {
    id: 'w15',
    slug: 'eleceed',
    type: 'webtoon',
    title: 'Eleceed',
    alternativeTitles: ['일렉시드'],
    synopsis: "Jiwoo, un lycéen avec des réflexes surhumains, rencontre Kayden, un puissant éveillé qui prend la forme d'un chat. Sous la tutelle de Kayden, Jiwoo va développer ses pouvoirs et entrer dans le monde dangereux des éveillés.",
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    genres: [
      { id: 'action', name: 'Action' },
      { id: 'comedy', name: 'Comédie' },
      { id: 'supernatural', name: 'Surnaturel' },
    ],
    authors: [{ id: 'sonho', name: 'Son Jeho', avatarUrl: '/kami-sama.png' }],
    illustrators: [{ id: 'zin', name: 'Zinu', avatarUrl: '/kami-sama.png' }],
    publishers: [PUBLISHERS.naver],
    status: 'ongoing',
    year: 2018,
    rating: 8.7,
    ratingCount: 5100,
    volumes: Array.from({ length: 8 }, (_, i) => ({
      id: `elec-v${i + 1}`,
      number: i + 1,
      coverUrl: '/kami-sama.png',
      pageCount: 240,
      releaseDate: `${2021 + i}-01-01`,
    })),
    chapters: Array.from({ length: 300 }, (_, i) => ({
      id: `elec-c${i + 1}`,
      number: i + 1,
      pageCount: 18,
      releaseDate: `${2018 + Math.floor(i / 40)}-${String((i % 12) + 1).padStart(2, '0')}-01`,
    })),
    totalChapters: 300,
    languages: ['fr', 'en', 'ko'],
    formats: ['digital'],
    tags: ['éveillés', 'combat', 'mentor'],
    themes: ['croissance', 'amitié', 'pouvoir'],
    mainCharacters: [
      { id: 'jiwoo', name: 'Jiwoo', role: 'main' },
      { id: 'kayden', name: 'Kayden', role: 'main' },
    ],
  },
]

// ── Library Entries (user's personal library) ──────────────────────────────
export const MY_LIBRARY: LibraryEntry[] = [
  {
    work: LIBRARY_WORKS[0],
    readingStatus: 'reading',
    progress: {
      currentChapter: 156,
      currentPage: 0,
      totalPagesRead: 3120,
      totalChaptersRead: 156,
      percentComplete: 41,
      lastReadAt: '2026-07-28T22:30:00Z',
      estimatedTimeLeft: '45h',
    },
    isFavorite: true,
    isDownloaded: true,
    rating: 9.5,
    dateAdded: '2024-01-15T10:00:00Z',
    lastReadAt: '2026-07-28T22:30:00Z',
    lastReadChapter: 156,
  },
  {
    work: LIBRARY_WORKS[1],
    readingStatus: 'reading',
    progress: {
      currentChapter: 890,
      currentPage: 0,
      totalPagesRead: 15130,
      totalChaptersRead: 890,
      percentComplete: 79,
      lastReadAt: '2026-07-27T18:15:00Z',
      estimatedTimeLeft: '22h',
    },
    isFavorite: true,
    isDownloaded: false,
    rating: 9.2,
    dateAdded: '2023-06-10T14:00:00Z',
    lastReadAt: '2026-07-27T18:15:00Z',
    lastReadChapter: 890,
  },
  {
    work: LIBRARY_WORKS[2],
    readingStatus: 'completed',
    progress: {
      currentChapter: 200,
      currentPage: 0,
      totalPagesRead: 4000,
      totalChaptersRead: 200,
      percentComplete: 100,
      lastReadAt: '2026-07-15T10:00:00Z',
    },
    isFavorite: true,
    isDownloaded: true,
    rating: 9.0,
    dateAdded: '2024-03-20T09:00:00Z',
    lastReadAt: '2026-07-15T10:00:00Z',
    lastReadChapter: 200,
  },
  {
    work: LIBRARY_WORKS[3],
    readingStatus: 'completed',
    progress: {
      currentChapter: 108,
      currentPage: 0,
      totalPagesRead: 2052,
      totalChaptersRead: 108,
      percentComplete: 100,
      lastReadAt: '2026-06-20T16:45:00Z',
    },
    isFavorite: true,
    isDownloaded: false,
    rating: 9.3,
    dateAdded: '2024-05-01T11:00:00Z',
    lastReadAt: '2026-06-20T16:45:00Z',
    lastReadChapter: 108,
  },
  {
    work: LIBRARY_WORKS[4],
    readingStatus: 'reading',
    progress: {
      currentChapter: 320,
      currentPage: 0,
      totalPagesRead: 6400,
      totalChaptersRead: 320,
      percentComplete: 53,
      lastReadAt: '2026-07-29T08:00:00Z',
      estimatedTimeLeft: '18h',
    },
    isFavorite: false,
    isDownloaded: true,
    dateAdded: '2024-08-12T15:30:00Z',
    lastReadAt: '2026-07-29T08:00:00Z',
    lastReadChapter: 320,
  },
  {
    work: LIBRARY_WORKS[5],
    readingStatus: 'completed',
    progress: {
      currentChapter: 162,
      currentPage: 0,
      totalPagesRead: 3240,
      totalChaptersRead: 162,
      percentComplete: 100,
      lastReadAt: '2026-05-10T20:00:00Z',
    },
    isFavorite: true,
    isDownloaded: false,
    rating: 9.4,
    dateAdded: '2023-12-01T08:00:00Z',
    lastReadAt: '2026-05-10T20:00:00Z',
    lastReadChapter: 162,
  },
  {
    work: LIBRARY_WORKS[6],
    readingStatus: 'plan-to-read',
    progress: {
      currentChapter: 0,
      currentPage: 0,
      totalPagesRead: 0,
      totalChaptersRead: 0,
      percentComplete: 0,
      lastReadAt: '',
    },
    isFavorite: false,
    isDownloaded: false,
    dateAdded: '2026-07-01T12:00:00Z',
  },
  {
    work: LIBRARY_WORKS[7],
    readingStatus: 'reading',
    progress: {
      currentChapter: 145,
      currentPage: 0,
      totalPagesRead: 2900,
      totalChaptersRead: 145,
      percentComplete: 58,
      lastReadAt: '2026-07-28T23:45:00Z',
      estimatedTimeLeft: '8h',
    },
    isFavorite: true,
    isDownloaded: true,
    rating: 9.6,
    dateAdded: '2024-02-14T18:00:00Z',
    lastReadAt: '2026-07-28T23:45:00Z',
    lastReadChapter: 145,
  },
  {
    work: LIBRARY_WORKS[8],
    readingStatus: 'completed',
    progress: {
      currentChapter: 200,
      currentPage: 0,
      totalPagesRead: 4000,
      totalChaptersRead: 200,
      percentComplete: 100,
      lastReadAt: '2026-04-05T14:30:00Z',
    },
    isFavorite: true,
    isDownloaded: false,
    rating: 9.3,
    dateAdded: '2023-09-20T10:00:00Z',
    lastReadAt: '2026-04-05T14:30:00Z',
    lastReadChapter: 200,
  },
  {
    work: LIBRARY_WORKS[9],
    readingStatus: 'reading',
    progress: {
      currentChapter: 90,
      currentPage: 0,
      totalPagesRead: 1800,
      totalChaptersRead: 90,
      percentComplete: 41,
      lastReadAt: '2026-07-26T19:20:00Z',
      estimatedTimeLeft: '12h',
    },
    isFavorite: false,
    isDownloaded: false,
    dateAdded: '2025-01-10T16:00:00Z',
    lastReadAt: '2026-07-26T19:20:00Z',
    lastReadChapter: 90,
  },
  {
    work: LIBRARY_WORKS[10],
    readingStatus: 'on-hold',
    progress: {
      currentChapter: 45,
      currentPage: 0,
      totalPagesRead: 900,
      totalChaptersRead: 45,
      percentComplete: 14,
      lastReadAt: '2026-03-15T11:00:00Z',
    },
    isFavorite: false,
    isDownloaded: false,
    dateAdded: '2024-11-05T09:00:00Z',
    lastReadAt: '2026-03-15T11:00:00Z',
    lastReadChapter: 45,
  },
  {
    work: LIBRARY_WORKS[11],
    readingStatus: 'reading',
    progress: {
      currentChapter: 120,
      currentPage: 0,
      totalPagesRead: 2400,
      totalChaptersRead: 120,
      percentComplete: 60,
      lastReadAt: '2026-07-25T21:10:00Z',
      estimatedTimeLeft: '6h',
    },
    isFavorite: true,
    isDownloaded: true,
    rating: 8.9,
    dateAdded: '2024-07-01T13:00:00Z',
    lastReadAt: '2026-07-25T21:10:00Z',
    lastReadChapter: 120,
  },
]

// ── Collections ────────────────────────────────────────────────────────────
export const LIBRARY_COLLECTIONS: Collection[] = [
  {
    id: 'col1',
    slug: 'seinen-masters',
    name: 'Maîtres du Seinen',
    description: 'Les œuvres seinen les plus emblématiques, pour les lecteurs exigeants.',
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    type: 'official',
    works: LIBRARY_WORKS.filter((w) => w.genres.some((g) => g.id === 'seinen')).map((w) => ({
      id: w.id,
      slug: w.slug,
      type: w.type,
      title: w.title,
      coverUrl: w.coverUrl,
      rating: w.rating,
      status: w.status,
      genres: w.genres,
    })),
    workCount: 4,
  },
  {
    id: 'col2',
    slug: 'isekai-universe',
    name: 'Isekai & Reincarnation',
    description: 'Toutes les œuvres où les héros traversent un autre monde.',
    coverUrl: '/kami-sama.png',
    type: 'universe',
    works: [
      { id: 'w7', slug: 'mushoku-tensei', type: 'light-novel', title: 'Mushoku Tensei', coverUrl: '/kami-sama.png', rating: 9.0, status: 'completed', genres: [] },
      { id: 'w10', slug: 'the-beginning-after-the-end', type: 'manhwa', title: 'The Beginning After the End', coverUrl: '/kami-sama.png', rating: 8.8, status: 'ongoing', genres: [] },
    ],
    workCount: 2,
  },
  {
    id: 'col3',
    slug: 'masterpiece-manga',
    name: 'Chefs-d\'œuvre du Manga',
    description: 'Les mangas qui ont marqué l\'histoire du medium.',
    coverUrl: '/kami-sama.png',
    bannerUrl: '/kami-sama.png',
    type: 'official',
    works: [
      { id: 'w1', slug: 'berserk-the-golden-age', type: 'manga', title: 'Berserk', coverUrl: '/kami-sama.png', rating: 9.8, status: 'ongoing', genres: [] },
      { id: 'w3', slug: 'death-note', type: 'manga', title: 'Death Note', coverUrl: '/kami-sama.png', rating: 9.3, status: 'completed', genres: [] },
      { id: 'w5', slug: 'monster', type: 'manga', title: 'Monster', coverUrl: '/kami-sama.png', rating: 9.4, status: 'completed', genres: [] },
      { id: 'w8', slug: 'vinland-saga', type: 'manga', title: 'Vinland Saga', coverUrl: '/kami-sama.png', rating: 9.3, status: 'completed', genres: [] },
      { id: 'w10', slug: 'vagabond', type: 'manga', title: 'Vagabond', coverUrl: '/kami-sama.png', rating: 9.5, status: 'hiatus', genres: [] },
    ],
    workCount: 5,
  },
  {
    id: 'col4',
    slug: 'korean-wave',
    name: 'Hallyu — Manhwa & Webtoon',
    description: 'Les meilleurs manhwa et webtoons coréens.',
    coverUrl: '/kami-sama.png',
    type: 'franchise',
    works: LIBRARY_WORKS.filter((w) => w.type === 'manhwa' || w.type === 'webtoon').map((w) => ({
      id: w.id,
      slug: w.slug,
      type: w.type,
      title: w.title,
      coverUrl: w.coverUrl,
      rating: w.rating,
      status: w.status,
      genres: w.genres,
    })),
    workCount: 4,
  },
]

// ── Reading History ────────────────────────────────────────────────────────
export const READING_HISTORY: ReadingHistoryItem[] = [
  {
    work: { id: 'w8', slug: 'omniscient-reader', type: 'webtoon', title: 'Omniscient Reader\'s Viewpoint', coverUrl: '/kami-sama.png', rating: 9.6, status: 'completed', genres: [] },
    lastChapterRead: 145,
    lastPageRead: 18,
    progressPercent: 58,
    readAt: '2026-07-28T23:45:00Z',
    duration: '1h 20min',
  },
  {
    work: { id: 'w5', slug: 'tower-of-god', type: 'manhwa', title: 'Tower of God', coverUrl: '/kami-sama.png', rating: 8.9, status: 'ongoing', genres: [] },
    lastChapterRead: 320,
    lastPageRead: 15,
    progressPercent: 53,
    readAt: '2026-07-29T08:00:00Z',
    duration: '45min',
  },
  {
    work: { id: 'w1', slug: 'berserk-the-golden-age', type: 'manga', title: 'Berserk', coverUrl: '/kami-sama.png', rating: 9.8, status: 'ongoing', genres: [] },
    lastChapterRead: 156,
    lastPageRead: 12,
    progressPercent: 41,
    readAt: '2026-07-28T22:30:00Z',
    duration: '2h 10min',
  },
  {
    work: { id: 'w2', slug: 'one-piece', type: 'manga', title: 'One Piece', coverUrl: '/kami-sama.png', rating: 9.5, status: 'ongoing', genres: [] },
    lastChapterRead: 890,
    lastPageRead: 8,
    progressPercent: 79,
    readAt: '2026-07-27T18:15:00Z',
    duration: '1h 45min',
  },
  {
    work: { id: 'w11', slug: 'one-punch-man', type: 'manga', title: 'One-Punch Man', coverUrl: '/kami-sama.png', rating: 8.9, status: 'ongoing', genres: [] },
    lastChapterRead: 120,
    lastPageRead: 10,
    progressPercent: 60,
    readAt: '2026-07-25T21:10:00Z',
    duration: '50min',
  },
]

// ── Downloads ──────────────────────────────────────────────────────────────
export const DOWNLOADS: DownloadItem[] = [
  {
    work: { id: 'w1', slug: 'berserk-the-golden-age', type: 'manga', title: 'Berserk', coverUrl: '/kami-sama.png', rating: 9.8, status: 'ongoing', genres: [] },
    chapters: Array.from({ length: 156 }, (_, i) => ({
      id: `berserk-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: '',
    })),
    status: 'downloaded',
    progress: 100,
    fileSize: '2.1 Go',
    downloadedAt: '2026-07-28T22:00:00Z',
  },
  {
    work: { id: 'w8', slug: 'omniscient-reader', type: 'webtoon', title: 'Omniscient Reader\'s Viewpoint', coverUrl: '/kami-sama.png', rating: 9.6, status: 'completed', genres: [] },
    chapters: Array.from({ length: 145 }, (_, i) => ({
      id: `orv-c${i + 1}`,
      number: i + 1,
      pageCount: 18,
      releaseDate: '',
    })),
    status: 'downloaded',
    progress: 100,
    fileSize: '1.8 Go',
    downloadedAt: '2026-07-27T19:00:00Z',
  },
  {
    work: { id: 'w5', slug: 'tower-of-god', type: 'manhwa', title: 'Tower of God', coverUrl: '/kami-sama.png', rating: 8.9, status: 'ongoing', genres: [] },
    chapters: Array.from({ length: 200 }, (_, i) => ({
      id: `tog-c${i + 1}`,
      number: i + 1,
      pageCount: 18,
      releaseDate: '',
    })),
    status: 'downloaded',
    progress: 100,
    fileSize: '1.5 Go',
    downloadedAt: '2026-07-26T20:00:00Z',
  },
  {
    work: { id: 'w11', slug: 'one-punch-man', type: 'manga', title: 'One-Punch Man', coverUrl: '/kami-sama.png', rating: 8.9, status: 'ongoing', genres: [] },
    chapters: Array.from({ length: 60 }, (_, i) => ({
      id: `opm-c${i + 1}`,
      number: i + 1,
      pageCount: 20,
      releaseDate: '',
    })),
    status: 'downloading',
    progress: 30,
    fileSize: '340 Mo',
    downloadedAt: '',
  },
]

// ── Helpers ────────────────────────────────────────────────────────────────

export function getLibraryEntry(workSlug: string): LibraryEntry | undefined {
  return MY_LIBRARY.find((e) => e.work.slug === workSlug)
}

export function getLibraryWork(slug: string): Work | undefined {
  return LIBRARY_WORKS.find((w) => w.slug === slug)
}

export function getWorksByType(type: Work['type']): Work[] {
  return LIBRARY_WORKS.filter((w) => w.type === type)
}

export function getTrendingWorks(): Work[] {
  return [...LIBRARY_WORKS].sort((a, b) => b.rating - a.rating).slice(0, 8)
}

export function getNewWorks(): Work[] {
  return [...LIBRARY_WORKS].sort((a, b) => b.year - a.year).slice(0, 8)
}

export function getPopularWorks(): Work[] {
  return [...LIBRARY_WORKS].sort((a, b) => b.ratingCount - a.ratingCount).slice(0, 8)
}

export function getContinueReading(): LibraryEntry[] {
  return MY_LIBRARY.filter((e) => e.readingStatus === 'reading')
    .sort((a, b) => new Date(b.lastReadAt || '').getTime() - new Date(a.lastReadAt || '').getTime())
}

export function getFavorites(): LibraryEntry[] {
  return MY_LIBRARY.filter((e) => e.isFavorite)
}

export function getDownloads(): DownloadItem[] {
  return DOWNLOADS
}

export function searchLibrary(query: string): Work[] {
  const q = query.toLowerCase()
  return LIBRARY_WORKS.filter(
    (w) =>
      w.title.toLowerCase().includes(q) ||
      w.alternativeTitles.some((t) => t.toLowerCase().includes(q)) ||
      w.authors.some((a) => a.name.toLowerCase().includes(q)) ||
      w.genres.some((g) => g.name.toLowerCase().includes(q)),
  )
}

export function getAllWorkTypes(): { id: Work['type']; label: string }[] {
  return [
    { id: 'manga', label: 'Manga' },
    { id: 'manhwa', label: 'Manhwa' },
    { id: 'manhua', label: 'Manhua' },
    { id: 'webtoon', label: 'Webtoon' },
    { id: 'light-novel', label: 'Light Novel' },
    { id: 'novel', label: 'Novel' },
    { id: 'comics', label: 'Comics' },
    { id: 'bande-dessinee', label: 'Bande Dessinée' },
    { id: 'artbook', label: 'Artbook' },
    { id: 'one-shot', label: 'One-Shot' },
  ]
}

export function getAllGenres(): { id: string; label: string }[] {
  return LIBRARY_GENRES.map((g) => ({ id: g.id, label: g.name }))
}

export function getAllLanguages(): { id: string; label: string }[] {
  return [
    { id: 'fr', label: 'Français' },
    { id: 'en', label: 'Anglais' },
    { id: 'ja', label: 'Japonais' },
    { id: 'ko', label: 'Coréen' },
    { id: 'zh', label: 'Chinois' },
  ]
}
