import type { StatusTone } from '@/components/dash/status-badge'

export type UsageFrequency = 'high' | 'medium' | 'low'

export interface TagSeriesRef {
  id: string
  title: string
  year: number
}

export interface TagItem {
  id: string
  slug: string
  name: string
  seriesCount: number
  peopleCount: number
  usageFrequency: UsageFrequency
  lastUsedAt: string
  topSeries: TagSeriesRef[]
  updatedAt: string
  updatedBy: string
}

export const USAGE_FREQUENCY_LABEL: Record<UsageFrequency, string> = {
  high: 'High',
  medium: 'Medium',
  low: 'Low',
}

export const USAGE_FREQUENCY_TONE: Record<UsageFrequency, StatusTone> = {
  high: 'success',
  medium: 'info',
  low: 'neutral',
}

export const TAG_MOCK: TagItem[] = [
  {
    id: 't1',
    slug: 'isekai',
    name: 'isekai',
    seriesCount: 3,
    peopleCount: 5,
    usageFrequency: 'high',
    lastUsedAt: '2h ago',
    topSeries: [
      { id: 'ser-001', title: 'Eternal Frost', year: 2024 },
      { id: 'ser-006', title: 'Hollow Kingdom', year: 2025 },
    ],
    updatedAt: '2h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't2',
    slug: 'magic',
    name: 'magic',
    seriesCount: 4,
    peopleCount: 3,
    usageFrequency: 'high',
    lastUsedAt: '4h ago',
    topSeries: [
      { id: 'ser-001', title: 'Eternal Frost', year: 2024 },
      { id: 'ser-004', title: 'Spirit Veil', year: 2024 },
      { id: 'ser-011', title: 'Ember Crown', year: 2025 },
    ],
    updatedAt: '4h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't3',
    slug: 'longevity',
    name: 'longevity',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-001', title: 'Eternal Frost', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't4',
    slug: 'travel',
    name: 'travel',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '1d ago',
    topSeries: [
      { id: 'ser-001', title: 'Eternal Frost', year: 2024 },
      { id: 'ser-013', title: "Ocean's Whisper", year: 2025 },
    ],
    updatedAt: '1d ago',
    updatedBy: 'admin',
  },
  {
    id: 't5',
    slug: 'samurai',
    name: 'samurai',
    seriesCount: 2,
    peopleCount: 4,
    usageFrequency: 'medium',
    lastUsedAt: '6h ago',
    topSeries: [
      { id: 'ser-002', title: 'Crimson Blade', year: 2023 },
      { id: 'ser-010', title: 'Neon Samurai', year: 2024 },
    ],
    updatedAt: '6h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't6',
    slug: 'revenge',
    name: 'revenge',
    seriesCount: 2,
    peopleCount: 2,
    usageFrequency: 'medium',
    lastUsedAt: '1d ago',
    topSeries: [
      { id: 'ser-002', title: 'Crimson Blade', year: 2023 },
      { id: 'ser-009', title: 'Blade of the Fallen', year: 2025 },
    ],
    updatedAt: '1d ago',
    updatedBy: 'admin',
  },
  {
    id: 't7',
    slug: 'feudal',
    name: 'feudal',
    seriesCount: 1,
    peopleCount: 2,
    usageFrequency: 'low',
    lastUsedAt: '2w ago',
    topSeries: [
      { id: 'ser-002', title: 'Crimson Blade', year: 2023 },
    ],
    updatedAt: '2w ago',
    updatedBy: 'admin',
  },
  {
    id: 't8',
    slug: 'mecha',
    name: 'mecha',
    seriesCount: 2,
    peopleCount: 3,
    usageFrequency: 'medium',
    lastUsedAt: '8h ago',
    topSeries: [
      { id: 'ser-003', title: 'Neon Orbit', year: 2025 },
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '8h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't9',
    slug: 'cyberpunk',
    name: 'cyberpunk',
    seriesCount: 2,
    peopleCount: 2,
    usageFrequency: 'medium',
    lastUsedAt: '6h ago',
    topSeries: [
      { id: 'ser-003', title: 'Neon Orbit', year: 2025 },
      { id: 'ser-010', title: 'Neon Samurai', year: 2024 },
    ],
    updatedAt: '6h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't10',
    slug: 'space',
    name: 'space',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '4h ago',
    topSeries: [
      { id: 'ser-003', title: 'Neon Orbit', year: 2025 },
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '4h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't11',
    slug: 'spirits',
    name: 'spirits',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-004', title: 'Spirit Veil', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't12',
    slug: 'japanese-folklore',
    name: 'japanese folklore',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '6h ago',
    topSeries: [
      { id: 'ser-004', title: 'Spirit Veil', year: 2024 },
      { id: 'ser-014', title: 'Crimson Vow', year: 2024 },
    ],
    updatedAt: '6h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't13',
    slug: 'mystery',
    name: 'mystery',
    seriesCount: 3,
    peopleCount: 2,
    usageFrequency: 'high',
    lastUsedAt: '4h ago',
    topSeries: [
      { id: 'ser-003', title: 'Neon Orbit', year: 2025 },
      { id: 'ser-004', title: 'Spirit Veil', year: 2024 },
      { id: 'ser-010', title: 'Neon Samurai', year: 2024 },
    ],
    updatedAt: '4h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't14',
    slug: 'high-school',
    name: 'high school',
    seriesCount: 2,
    peopleCount: 3,
    usageFrequency: 'medium',
    lastUsedAt: '3d ago',
    topSeries: [
      { id: 'ser-005', title: 'After School Skies', year: 2023 },
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '3d ago',
    updatedBy: 'admin',
  },
  {
    id: 't15',
    slug: 'coming-of-age',
    name: 'coming-of-age',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '3d ago',
    topSeries: [
      { id: 'ser-005', title: 'After School Skies', year: 2023 },
      { id: 'ser-007', title: 'Last Serve', year: 2024 },
    ],
    updatedAt: '3d ago',
    updatedBy: 'admin',
  },
  {
    id: 't16',
    slug: 'friendship',
    name: 'friendship',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '3d ago',
    topSeries: [
      { id: 'ser-005', title: 'After School Skies', year: 2023 },
      { id: 'ser-007', title: 'Last Serve', year: 2024 },
    ],
    updatedAt: '3d ago',
    updatedBy: 'admin',
  },
  {
    id: 't17',
    slug: 'dark-fantasy',
    name: 'dark fantasy',
    seriesCount: 3,
    peopleCount: 4,
    usageFrequency: 'high',
    lastUsedAt: '5h ago',
    topSeries: [
      { id: 'ser-006', title: 'Hollow Kingdom', year: 2025 },
      { id: 'ser-009', title: 'Blade of the Fallen', year: 2025 },
      { id: 'ser-011', title: 'Ember Crown', year: 2025 },
    ],
    updatedAt: '5h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't18',
    slug: 'amnesia',
    name: 'amnesia',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-006', title: 'Hollow Kingdom', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't19',
    slug: 'cursed-weapon',
    name: 'cursed weapon',
    seriesCount: 2,
    peopleCount: 2,
    usageFrequency: 'medium',
    lastUsedAt: '5h ago',
    topSeries: [
      { id: 'ser-006', title: 'Hollow Kingdom', year: 2025 },
      { id: 'ser-009', title: 'Blade of the Fallen', year: 2025 },
    ],
    updatedAt: '5h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't20',
    slug: 'volleyball',
    name: 'volleyball',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '2w ago',
    topSeries: [
      { id: 'ser-007', title: 'Last Serve', year: 2024 },
    ],
    updatedAt: '2w ago',
    updatedBy: 'admin',
  },
  {
    id: 't21',
    slug: 'redemption',
    name: 'redemption',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '1d ago',
    topSeries: [
      { id: 'ser-007', title: 'Last Serve', year: 2024 },
      { id: 'ser-009', title: 'Blade of the Fallen', year: 2025 },
    ],
    updatedAt: '1d ago',
    updatedBy: 'admin',
  },
  {
    id: 't22',
    slug: 'teamwork',
    name: 'teamwork',
    seriesCount: 2,
    peopleCount: 1,
    usageFrequency: 'medium',
    lastUsedAt: '1d ago',
    topSeries: [
      { id: 'ser-007', title: 'Last Serve', year: 2024 },
      { id: 'ser-012', title: 'Thunder League', year: 2025 },
    ],
    updatedAt: '1d ago',
    updatedBy: 'admin',
  },
  {
    id: 't23',
    slug: 'academy',
    name: 'academy',
    seriesCount: 1,
    peopleCount: 2,
    usageFrequency: 'low',
    lastUsedAt: '2d ago',
    topSeries: [
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '2d ago',
    updatedBy: 'admin',
  },
  {
    id: 't24',
    slug: 'military',
    name: 'military',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '2d ago',
    topSeries: [
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '2d ago',
    updatedBy: 'admin',
  },
  {
    id: 't25',
    slug: 'alien-technology',
    name: 'alien technology',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '2d ago',
    topSeries: [
      { id: 'ser-008', title: 'Starfall Academy', year: 2025 },
    ],
    updatedAt: '2d ago',
    updatedBy: 'admin',
  },
  {
    id: 't26',
    slug: 'ronin',
    name: 'ronin',
    seriesCount: 1,
    peopleCount: 2,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-010', title: 'Neon Samurai', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't27',
    slug: 'neo-tokyo',
    name: 'neo-tokyo',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-010', title: 'Neon Samurai', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't28',
    slug: 'royalty',
    name: 'royalty',
    seriesCount: 1,
    peopleCount: 2,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-011', title: 'Ember Crown', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't29',
    slug: 'fire-magic',
    name: 'fire magic',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-011', title: 'Ember Crown', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't30',
    slug: 'political-intrigue',
    name: 'political intrigue',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-011', title: 'Ember Crown', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't31',
    slug: 'soccer',
    name: 'soccer',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-012', title: 'Thunder League', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't32',
    slug: 'elemental-power',
    name: 'elemental power',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-012', title: 'Thunder League', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't33',
    slug: 'underdog',
    name: 'underdog',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-012', title: 'Thunder League', year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't34',
    slug: 'marine',
    name: 'marine',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-013', title: "Ocean's Whisper", year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't35',
    slug: 'romance',
    name: 'romance',
    seriesCount: 3,
    peopleCount: 2,
    usageFrequency: 'high',
    lastUsedAt: '4h ago',
    topSeries: [
      { id: 'ser-005', title: 'After School Skies', year: 2023 },
      { id: 'ser-013', title: "Ocean's Whisper", year: 2025 },
      { id: 'ser-014', title: 'Crimson Vow', year: 2024 },
    ],
    updatedAt: '4h ago',
    updatedBy: 'auto-import',
  },
  {
    id: 't36',
    slug: 'hometown',
    name: 'hometown',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-013', title: "Ocean's Whisper", year: 2025 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't37',
    slug: 'vampire',
    name: 'vampire',
    seriesCount: 1,
    peopleCount: 2,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-014', title: 'Crimson Vow', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
  {
    id: 't38',
    slug: 'immortality',
    name: 'immortality',
    seriesCount: 1,
    peopleCount: 1,
    usageFrequency: 'low',
    lastUsedAt: '1w ago',
    topSeries: [
      { id: 'ser-014', title: 'Crimson Vow', year: 2024 },
    ],
    updatedAt: '1w ago',
    updatedBy: 'admin',
  },
]

export function getTagStats(tags: TagItem[]) {
  const total = tags.length
  const totalSeriesUsage = tags.reduce((acc, t) => acc + t.seriesCount, 0)
  const totalPeopleUsage = tags.reduce((acc, t) => acc + t.peopleCount, 0)
  const unused = tags.filter((t) => t.seriesCount === 0).length
  const highUsage = tags.filter((t) => t.usageFrequency === 'high').length
  const avgSeriesPerTag = total > 0 ? totalSeriesUsage / total : 0

  return {
    total,
    totalSeriesUsage,
    totalPeopleUsage,
    unused,
    highUsage,
    avgSeriesPerTag,
  }
}
